#import <assimp/aabb.h>
#import <assimp/anim.h>
#import <assimp/camera.h>
#import <assimp/cexport.h>
#import <assimp/cfileio.h>
#import <assimp/cimport.h>
#import <assimp/color4.h>
#import <assimp/commonMetaData.h>
#import <assimp/config.h>
#import <assimp/defs.h>
#import <assimp/GltfMaterial.h>
#import <assimp/importerdesc.h>
#import <assimp/light.h>
#import <assimp/material.h>
#import <assimp/matrix3x3.h>
#import <assimp/matrix4x4.h>
#import <assimp/mesh.h>
#import <assimp/metadata.h>
#import <assimp/postprocess.h>
#import <assimp/quaternion.h>
#import <assimp/scene.h>
#import <assimp/texture.h>
#import <assimp/types.h>
#import <assimp/vector2.h>
#import <assimp/vector3.h>
#import <assimp/version.h>
