#if !canImport(ObjectiveC)
import XCTest

extension AssimpTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AssimpTests = [
        ("testFailingInitializer", testFailingInitializer),
        ("testLoadAiSceneDAE", testLoadAiSceneDAE),
        ("testLoadAiSceneObj", testLoadAiSceneObj),
        ("testVec2fFromAiVector2D", testVec2fFromAiVector2D),
        ("testVec3fFromAiVector3D", testVec3fFromAiVector3D),
        ("testVersion", testVersion)
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AssimpTests.__allTests__AssimpTests)
    ]
}
#endif
