name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux-test-build-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: ["latest"]
    container:
      image: swift:${{ matrix.swift }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Restore APT cache
        uses: actions/cache@v3.3.1
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt
      - name: Restore cached SPM dependencies
        uses: actions/cache@v3.3.1
        with:
          path: |
            .build/repositories
          key: ${{ runner.os }}-spm-repos-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-repos-
      - name: Install dependencies
        run: |
          # update dependency source list to more modern linux distribution
          # echo -e "deb http://archive.ubuntu.com/ubuntu focal main restricted universe multiverse" >> /etc/apt/sources.list
          apt update
          apt-get install -y -qq pkg-config libassimp-dev
      - name: Test
        run: make test
      - name: Build Release
        run: make build-release
