name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos-test-build-release-xcode:
    runs-on: macos-14
    strategy:
      matrix:
        xcode: ["14.3.1", "15.0"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Restore cached Homebrew dependencies
        uses: actions/cache@v3.3.1
        with:
          path: |
            ~/Library/Caches/Homebrew/assimp--*
            ~/Library/Caches/Homebrew/downloads/*--assimp-*
          key: ${{ runner.os }}-brew-assimp-${{ hashFiles('.github/brew-formulae') }}
          restore-keys: ${{ runner.os }}-brew-assimp-
      - name: Restore cached SPM dependencies
        uses: actions/cache@v3.3.1
        with:
          path: |
            .build/repositories
          key: ${{ runner.os }}-spm-repos-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-repos-
      - name: Install dependencies
        run: |
          brew install assimp
      - name: Test
        run: make test
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      - name: Upload test artifacts
        if: failure()
        uses: actions/upload-artifact@v3.1.2
        with:
          name: test-artifacts-${{ matrix.xcode }}-${{ github.run_id }}
          path: |
            .build/**/*.json
            .build/**/*.xctest
      - name: Build Release
        run: make build-release
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      - name: Upload build artifacts
        if: failure()
        uses: actions/upload-artifact@v3.1.2
        with:
          name: build-artifacts-${{ matrix.xcode }}-${{ github.run_id }}
          path: |
            *.lcov
            .build/*.yaml
            .build/**/*.a
            .build/**/*.so
            .build/**/*.dylib
            .build/**/*.dSYM 
            .build/**/*.json
